"""
This type stub file was generated by pyright.
"""

def post_processor(app=..., project=..., design=..., version=...): # -> PostProcessor3D | PostProcessor3DLayout | PostProcessorCircuit | PostProcessorIcepak | None:
    """PostProcessor.

    Returns
    -------
    :class:`ansys.aedt.core.visualization.post.post_common_3d.PostProcessor3D` or
    :class:`ansys.aedt.core.visualization.post.post_icepak.PostProcessorIcepak` or
    :class:`ansys.aedt.core.visualization.post.post_circuit.PostProcessorCircuit`
        PostProcessor object.
    """
    ...

