"""
This type stub file was generated by pyright.
"""

"""This module contains the ``AedtVersions`` class.

The constant ``CURRENT_STABLE_AEDT_VERSION`` set in this module should be updated
every time a new stable version is released.
Ideally, it should be the same as ``conftest.default_version``"""
CURRENT_STABLE_AEDT_VERSION = ...
class AedtVersions:
    """Class to get the AEDT versions on the system.

    It caches the data to avoid inspecting the environment variables multiple times."""
    def __init__(self) -> None:
        ...
    
    @property
    def list_installed_ansysem(self): # -> list[str]:
        """Return a list of installed AEDT versions on ``ANSYSEM_ROOT``.

        The list is ordered: first normal versions, then client versions, finally student versions."""
        ...
    
    @property
    def installed_versions(self): # -> dict[Any, Any]:
        """Get the installed AEDT versions.

        This method returns a dictionary, with the version as the key and installation path
        as the value."""
        ...
    
    @property
    def stable_versions(self): # -> list[Any]:
        """Get all stable versions installed on the system"""
        ...
    
    @property
    def current_version(self): # -> str:
        """Get the most recent stable AEDT version."""
        ...
    
    @property
    def current_student_version(self): # -> str:
        """Get the current stable AEDT student version."""
        ...
    
    @property
    def latest_version(self): # -> str:
        """Get the latest AEDT version, even if it is pre-release."""
        ...
    
    @staticmethod
    def get_version_env_variable(version_id): # -> str:
        """Get the environment variable for the AEDT version.

        Parameters
        ----------
        version_id : str
            Full AEDT version number. For example, ``"2021.2"``.

        Returns
        -------
        str
            Environment variable for the version.

        Examples
        --------
        >>> from ansys.aedt.core import desktop
        >>> desktop.get_version_env_variable("2025.1")
        'ANSYSEM_ROOT212'

        """
        ...
    


aedt_versions = ...
