"""
This type stub file was generated by pyright.
"""

from ansys.aedt.core.generic.general_methods import pyaedt_function_handler
from ansys.aedt.core.visualization.report.common import CommonReport

"""
This module contains this class: `EMIReceiver`.

This module provides all functionalities for creating and editing reports.

"""
class EMIReceiver(CommonReport):
    """Provides for managing EMI receiver reports."""
    def __init__(self, app, setup_name, expressions=...) -> None:
        ...
    
    @property
    def net(self): # -> str:
        """Net attached to the EMI receiver.

        Returns
        -------
        str
            Net name.
        """
        ...
    
    @net.setter
    def net(self, value): # -> None:
        ...
    
    @property
    def band(self):
        """Band attached to the EMI receiver.

        Returns
        -------
        str
            Band name.
        """
        ...
    
    @band.setter
    def band(self, value): # -> None:
        ...
    
    @property
    def rbw(self):
        """RBW attached to the EMI receiver.

        Returns
        -------
        str
            RBW setting.
        """
        ...
    
    @rbw.setter
    def rbw(self, value): # -> None:
        ...
    
    @property
    def rbw_factor(self):
        """RBW Factor attached to the EMI receiver.

        Returns
        -------
        str
            RBW Factor setting.
        """
        ...
    
    @rbw_factor.setter
    def rbw_factor(self, value): # -> None:
        ...
    
    @property
    def emission(self): # -> str:
        """Emission test.

        Options are ``"CE"`` and ``"RE"``.

        Returns
        -------
        str
            Emission.
        """
        ...
    
    @emission.setter
    def emission(self, value): # -> None:
        ...
    
    @property
    def time_start(self):
        """Time start value.

        Returns
        -------
        str
            Time start.
        """
        ...
    
    @time_start.setter
    def time_start(self, value): # -> None:
        ...
    
    @property
    def time_stop(self):
        """Time stop value.

        Returns
        -------
        str
            Time stop.
        """
        ...
    
    @time_stop.setter
    def time_stop(self, value): # -> None:
        ...
    
    @pyaedt_function_handler()
    def create(self, name=...): # -> Self:
        """Create an EMI receiver report.

        Parameters
        ----------
        name : str, optional
            Plot name. The default is ``None``, in which case
            the default name is used.

        Returns
        -------
        bool
            ``True`` when successful, ``False`` when failed.
        """
        ...
    


