"""
This type stub file was generated by pyright.
"""

from ansys.aedt.core.generic.general_methods import pyaedt_function_handler
from ansys.aedt.core.visualization.plot.pyvista import CommonPlotter

pyvista_available = ...
class HDMPlotter(CommonPlotter):
    """
    Manages Hdm data to be plotted with ``pyvista``.

    Note: the methods in this class are just examples and subject
    to improvement and changes.
    """
    def __init__(self) -> None:
        ...
    
    @property
    def hdm_data(self): # -> Any | complex | list[complex] | list[Any] | tuple[Any, ...] | float | int | NDArray[Any] | list[Any | complex | float | int] | list[Any | complex | list[complex] | list[Any] | tuple[Any, ...]] | None:
        """Return the ``hds`` Data parsed."""
        ...
    
    @pyaedt_function_handler()
    def add_cad_model(self, filename, cad_color=..., opacity=..., units=...): # -> bool:
        """Add a ``stl`` file to the scenario.

        Parameters
        ----------
        filename : str
            Full path to stl file.

        Returns
        -------
        bool
            ``True`` if imported.
        """
        ...
    
    @pyaedt_function_handler()
    def add_hdm_bundle_from_file(self, filename, units=...): # -> None:
        """Add hdm bundle from file."""
        ...
    
    @pyaedt_function_handler()
    def plot_rays(self, snapshot_path=...): # -> Plotter:
        """Plot Rays read from an ``hdm`` file.

        Parameters
        ----------
        snapshot_path : str, optional
            Full path to exported image file. If ``None`` the plot will be shown.

        Returns
        -------
        :class:`pyvista.Plotter`


        Notes
        -----
        This method is intended to be an example of the usage that can be made of hdm file.

        """
        ...
    
    @pyaedt_function_handler()
    def plot_first_bounce_currents(self, snapshot_path=...): # -> None:
        """Plot First bounce of currents read from an ``hdm`` file.

        Parameters
        ----------
        snapshot_path : str, optional
            Full path to exported image file. If ``None`` the plot will be shown.

        Returns
        -------
        :class:`pyvista.Plotter`
        """
        ...
    


