"""
This type stub file was generated by pyright.
"""

class CreateBoundaryMixin:
    """Mixin that provides methods to apply boundary conditions.

    This mixin is designed to be used in classes that require boundary condition.
    Methods provided by this mixin should be implemented or extended by subclasses
    to define specific boundary condition behaviors.

    Example
    -------
    A class can use the default behavior or use a custom implementation.

    >>> class MyClass(CreateBoundaryMixin):
    >>>     def _create_boundary(self):
    >>>         # Use default behavior
    >>>         if boundary_type not in ("SpecificString"):
    >>>             return super()._create_boundary(name, props, boundary_type)
    >>>         # Custom implementation to create boundary conditions
    >>>         else:
    >>>             pass
    """
    ...


