"""
This type stub file was generated by pyright.
"""

from enum import Enum
from pyvista import Plotter
from ansys.tools.visualization_interface.backends.pyvista.widgets.button import Button

"""Provides the displacement arrows widget for the PyVista plotter."""
class CameraPanDirection(Enum):
    """Provides an enum with the available movement directions of the camera."""
    XUP = ...
    XDOWN = ...
    YUP = ...
    YDOWN = ...
    ZUP = ...
    ZDOWN = ...


class DisplacementArrow(Button):
    """Defines the arrow to draw and what it is to do.

    Parameters
    ----------
    plotter : Plotter
        Plotter to draw the buttons on.
    direction : CameraPanDirection
        Direction that the camera is to move.
    dark_mode : bool, optional
        Whether to activate the dark mode or not.
    """
    def __init__(self, plotter: Plotter, direction: CameraPanDirection, dark_mode: bool = ...) -> None:
        """Initialize the ``DisplacementArrow`` class."""
        ...
    
    def callback(self, state: bool) -> None:
        """Move the camera in the direction defined by the button.

        Parameters
        ----------
        state : bool
            Whether the state of the button, which is inherited from PyVista, is active.
            However, this parameter is unused by this ``callback`` method.

        """
        ...
    


