"""
This type stub file was generated by pyright.
"""

from pyvista import Plotter
from ansys.tools.visualization_interface.backends.pyvista.widgets.widget import PlotterWidget

"""Provides the ruler widget for the Visualization Interface Tool plotter."""
class Ruler(PlotterWidget):
    """Provides the ruler widget for the Visualization Interface Tool ``Plotter`` class.

    Parameters
    ----------
    plotter : ~pyvista.Plotter
        Provides the plotter to add the ruler widget to.
    dark_mode : bool, optional
        Whether to activate the dark mode or not.

    """
    def __init__(self, plotter: Plotter, dark_mode: bool = ...) -> None:
        """Initialize the ``Ruler`` class."""
        ...
    
    def callback(self, state: bool) -> None:
        """Remove or add the ruler widget actor upon click.

        Notes
        -----
        This method provides a callback function for the ruler widet.
        It is called every time the ruler widget is clicked.

        Parameters
        ----------
        state : bool
            Whether the state of the button, which is inherited from PyVista, is ``True``.

        """
        ...
    
    def update(self) -> None:
        """Define the configuration and representation of the ruler widget button."""
        ...
    


