"""
This type stub file was generated by pyright.
"""

import pyvista as pv
from typing import Any, List, Union
from ansys.tools.visualization_interface.types.edge_plot import EdgePlot

"""Provides the ``MeshObjectPlot`` class."""
class MeshObjectPlot:
    """Relates a custom object with a mesh, provided by the consumer library."""
    def __init__(self, custom_object: Any, mesh: Union[pv.PolyData, pv.MultiBlock], actor: pv.Actor = ..., edges: List[EdgePlot] = ...) -> None:
        """Relates a custom object with a mesh provided by the consumer library.

        This class is meant to be used as a mapper between a custom object and its mesh
        representation. It is used to store the custom object and its mesh, and to relate
        the custom object with its PyVista actor and its edges.

        Parameters
        ----------
        custom_object : Any
            Any object that the consumer library wants to relate with a mesh.
        mesh : Union[pv.PolyData, pv.MultiBlock]
            PyVista mesh that represents the custom object.
        actor : pv.Actor, default: None
            Actor of the mesh in the plotter.
        edges : List[EdgePlot], default: None
            Edges of the object if it has any.

        """
        ...
    
    @property
    def mesh(self) -> Union[pv.PolyData, pv.MultiBlock]:
        """Mesh of the object in PyVista format.

        Returns
        -------
        Union[pv.PolyData, pv.MultiBlock]
            Mesh of the object.

        """
        ...
    
    @mesh.setter
    def mesh(self, mesh: Union[pv.PolyData, pv.MultiBlock]): # -> None:
        """Set the mesh of the object in PyVista format.

        Parameters
        ----------
        mesh : Union[pv.PolyData, pv.MultiBlock]
            Mesh of the object.

        """
        ...
    
    @property
    def custom_object(self) -> Any:
        """Custom object.

        Returns
        -------
        Any
            Custom object.

        """
        ...
    
    @custom_object.setter
    def custom_object(self, custom_object: Any): # -> None:
        """Set the custom object.

        Parameters
        ----------
        custom_object : Any
            Custom object.

        """
        ...
    
    @property
    def actor(self) -> pv.Actor:
        """PyVista actor of the object in the plotter.

        Returns
        -------
        pv.Actor
            PyVista actor of the object.

        """
        ...
    
    @actor.setter
    def actor(self, actor: pv.Actor): # -> None:
        """Set the PyVista actor of the object in the plotter.

        Parameters
        ----------
        actor : pv.Actor
            PyVista actor of the object.

        """
        ...
    
    @property
    def edges(self) -> List[EdgePlot]:
        """Edges of the object.

        Returns
        -------
        List[EdgePlot]
            Edges of the object.

        """
        ...
    
    @edges.setter
    def edges(self, edges: List[EdgePlot]): # -> None:
        """Set the edges of the object.

        Parameters
        ----------
        edges : List[EdgePlot]
            Edges of the object.

        """
        ...
    
    @property
    def name(self) -> str:
        """Name of the object.

        Returns
        -------
        str
            Name of the object.

        """
        ...
    


