"""
This type stub file was generated by pyright.
"""

from enum import Enum

"""Provides an enum with the color to use for the plotter actors."""
class Color(Enum):
    """Provides an enum with the color to use for the plotter actors."""
    DEFAULT = ...
    PICKED = ...
    EDGE = ...
    PICKED_EDGE = ...


