"""
This type stub file was generated by pyright.
"""

import pyvista as pv
import numpy as np
from abc import abstractmethod
from typing import Any, Dict, List, Optional, TYPE_CHECKING, Union
from ansys.tools.visualization_interface.backends._base import BaseBackend
from ansys.tools.visualization_interface.backends.pyvista.pyvista_interface import PyVistaInterface
from ansys.tools.visualization_interface.backends.pyvista.widgets.widget import PlotterWidget
from ansys.tools.visualization_interface.types.edge_plot import EdgePlot
from ansys.tools.visualization_interface.types.mesh_object_plot import MeshObjectPlot

"""Provides a wrapper to aid in plotting."""
_HAS_TRAME = ...
DARK_MODE_THRESHOLD = ...
if TYPE_CHECKING:
    ...
class PyVistaBackendInterface(BaseBackend):
    """Provides the interface for the Visualization Interface Tool plotter.

    This class is intended to be used as a base class for the custom plotters
    in the different PyAnsys libraries. It provides the basic plotter functionalities,
    such as adding objects and enabling widgets and picking capabilities. It also
    provides the ability to show the plotter using the `trame <https://kitware.github.io/trame/index.html>`_
    service.

    You can override the ``plot_iter()``, ``plot()``, and ``picked_operation()`` methods.
    The ``plot_iter()`` method is intended to plot a list of objects to the plotter, while the
    ``plot()`` method is intended to plot a single object to the plotter. The ``show()`` method is
    intended to show the plotter. The ``picked_operation()`` method is
    intended to perform an operation on the picked objects.

    Parameters
    ----------
    use_trame : Optional[bool], default: None
        Whether to activate the usage of the trame UI instead of the Python window.
    allow_picking : Optional[bool], default: False
        Whether to allow picking capabilities in the window. Incompatible with hovering.
        Picking will take precedence over hovering.
    allow_hovering : Optional[bool], default: False
        Whether to allow hovering capabilities in the window. Incompatible with picking.
        Picking will take precedence over hovering.
    plot_picked_names : Optional[bool], default: False
        Whether to plot the names of the picked objects.
    show_plane : Optional[bool], default: False
        Whether to show the plane in the plotter.
    use_qt : Optional[bool], default: False
        Whether to use the Qt backend for the plotter.
    show_qt : Optional[bool], default: True
        Whether to show the Qt window.
    """
    def __init__(self, use_trame: Optional[bool] = ..., allow_picking: Optional[bool] = ..., allow_hovering: Optional[bool] = ..., plot_picked_names: Optional[bool] = ..., show_plane: Optional[bool] = ..., use_qt: Optional[bool] = ..., show_qt: Optional[bool] = ..., **plotter_kwargs) -> None:
        """Initialize the ``use_trame`` parameter and save the current ``pv.OFF_SCREEN`` value."""
        ...
    
    @property
    def pv_interface(self) -> PyVistaInterface:
        """PyVista interface."""
        ...
    
    @property
    def scene(self) -> pv.Plotter:
        """PyVista scene."""
        ...
    
    def enable_widgets(self, dark_mode: bool = ...) -> None:
        """Enable the widgets for the plotter.

        Parameters
        ----------
        dark_mode : bool, default: False
            Whether to use dark mode for the widgets.
        """
        ...
    
    def add_widget(self, widget: Union[PlotterWidget, List[PlotterWidget]]): # -> None:
        """Add one or more custom widgets to the plotter.

        Parameters
        ----------
        widget : Union[PlotterWidget, List[PlotterWidget]]
            One or more custom widgets.

        """
        ...
    
    def select_object(self, custom_object: Union[MeshObjectPlot, EdgePlot], pt: np.ndarray) -> None:
        """Select a custom object in the plotter.

        This method highlights the edges of a body and adds a label. It also adds
        the object to the ``_picked_dict`` and the actor to the ``_picker_added_actors_map``.

        Parameters
        ----------
        custom_object : Union[MeshObjectPlot, EdgePlot]
            Custom object to select.
        pt : ~numpy.ndarray
            Set of points to determine the label position.

        """
        ...
    
    def unselect_object(self, custom_object: Union[MeshObjectPlot, EdgePlot]) -> None:
        """Unselect a custom object in the plotter.

        This method removes edge highlighting and the label from a plotter actor and removes
        the object from the Visualization Interface Tool object selection.

        Parameters
        ----------
        custom_object : Union[MeshObjectPlot, EdgePlot]
            Custom object to unselect.

        """
        ...
    
    def picker_callback(self, actor: pv.Actor) -> None:
        """Define the callback for the element picker.

        Parameters
        ----------
        actor : ~pyvista.Actor
            Actor to select for the picker.

        """
        ...
    
    def hover_callback(self, _widget, event_name) -> None:
        """Define the callback for the element hover.

        Parameters
        ----------
        actor : ~pyvista.Actor
            Actor to hover for the picker.

        """
        ...
    
    def compute_edge_object_map(self) -> Dict[pv.Actor, EdgePlot]:
        """Compute the mapping between plotter actors and ``EdgePlot`` objects.

        Returns
        -------
        Dict[~pyvista.Actor, EdgePlot]
            Dictionary defining the mapping between plotter actors and ``EdgePlot`` objects.

        """
        ...
    
    def enable_picking(self): # -> None:
        """Enable picking capabilities in the plotter."""
        ...
    
    def enable_hover(self): # -> None:
        """Enable hover capabilities in the plotter."""
        ...
    
    def disable_picking(self): # -> None:
        """Disable picking capabilities in the plotter."""
        ...
    
    def disable_hover(self): # -> None:
        """Disable hover capabilities in the plotter."""
        ...
    
    def show(self, plottable_object: Any = ..., screenshot: Optional[str] = ..., view_2d: Dict = ..., name_filter: str = ..., dark_mode: bool = ..., **plotting_options) -> List[Any]:
        """Plot and show any PyAnsys object.

        The types of objects supported are ``MeshObjectPlot``,
        ``pv.MultiBlock``, and ``pv.PolyData``.

        Parameters
        ----------
        plottable_object : Any, default: None
           Object or list of objects to plot.
        screenshot : str, default: None
            Path for saving a screenshot of the image that is being represented.
        view_2d : Dict, default: None
            Dictionary with the plane and the viewup vectors of the 2D plane.
        name_filter : str, default: None
            Regular expression with the desired name or names to include in the plotter.
        dark_mode : bool, default: False
            Whether to use dark mode for the widgets.
        **plotting_options : dict, default: None
            Keyword arguments. For allowable keyword arguments, see the
            :meth:`Plotter.add_mesh <pyvista.Plotter.add_mesh>` method.

        Returns
        -------
        List[Any]
            List with the picked bodies in the picked order.

        """
        ...
    
    def show_plotter(self, screenshot: Optional[str] = ...) -> None:
        """Show the plotter or start the `trame <https://kitware.github.io/trame/index.html>`_ service.

        Parameters
        ----------
        plotter : Plotter
            Visualization Interface Tool plotter with the meshes added.
        screenshot : str, default: None
            Path for saving a screenshot of the image that is being represented.

        """
        ...
    
    @abstractmethod
    def plot_iter(self, plottable_object: Any, name_filter: str = ..., **plotting_options): # -> None:
        """Plot one or more compatible objects to the plotter.

        Parameters
        ----------
        plottable_object : Any
            One or more objects to add.
        name_filter : str, default: None.
            Regular expression with the desired name or names  to include in the plotter.
        **plotting_options : dict, default: None
            Keyword arguments. For allowable keyword arguments, see the
            :meth:`Plotter.add_mesh <pyvista.Plotter.add_mesh>` method.

        """
        ...
    
    @abstractmethod
    def plot(self, plottable_object: Any, name_filter: str = ..., **plotting_options): # -> None:
        """Plot a single object to the plotter.

        Parameters
        ----------
        plottable_object : Any
            Object to add.
        name_filter : str
            Regular expression with the desired name or names to include in the plotter.
        **plotting_options : dict, default: None
            Keyword arguments. For allowable keyword arguments, see the
            :meth:`Plotter.add_mesh <pyvista.Plotter.add_mesh>` method.

        """
        ...
    
    def picked_operation(self) -> None:
        """Perform an operation on the picked objects."""
        ...
    


class PyVistaBackend(PyVistaBackendInterface):
    """Provides the generic plotter implementation for PyAnsys libraries.

    This class accepts ``MeshObjectPlot``, ``pv.MultiBlock`` and ``pv.PolyData`` objects.

    Parameters
    ----------
    use_trame : bool, default: None
        Whether to enable the use of `trame <https://kitware.github.io/trame/index.html>`_.
        The default is ``None``, in which case the ``USE_TRAME`` global setting
        is used.
    allow_picking : Optional[bool], default: False
        Whether to allow picking capabilities in the window. Incompatible with hovering.
        Picking will take precedence over hovering.
    allow_hovering : Optional[bool], default: False
        Whether to allow hovering capabilities in the window. Incompatible with picking.
        Picking will take precedence over hovering.
    plot_picked_names : bool, default: True
        Whether to plot the names of the picked objects.

    """
    def __init__(self, use_trame: Optional[bool] = ..., allow_picking: Optional[bool] = ..., allow_hovering: Optional[bool] = ..., plot_picked_names: Optional[bool] = ..., use_qt: Optional[bool] = ..., show_qt: Optional[bool] = ...) -> None:
        """Initialize the generic plotter."""
        ...
    
    @property
    def base_plotter(self): # -> Plotter:
        """Return the base plotter object."""
        ...
    
    def plot_iter(self, plotting_list: List[Any], name_filter: str = ..., **plotting_options) -> None:
        """Plot the elements of an iterable of any type of object to the scene.

        The types of objects supported are ``Body``, ``Component``, ``List[pv.PolyData]``,
        ``pv.MultiBlock``, and ``Sketch``.

        Parameters
        ----------
        plotting_list : List[Any]
            List of objects to plot.
        name_filter : str, default: None
            Regular expression with the desired name or names to include in the plotter.
        **plotting_options : dict, default: None
            Keyword arguments. For allowable keyword arguments, see the
            :meth:`Plotter.add_mesh <pyvista.Plotter.add_mesh>` method.

        """
        ...
    
    def plot(self, plottable_object: Any, name_filter: str = ..., **plotting_options): # -> None:
        """Plot a ``pyansys`` or ``PyVista`` object to the plotter.

        Parameters
        ----------
        plottable_object : Any
            Object to add.
        name_filter : str
            Regular expression with the desired name or names to include in the plotter.
        **plotting_options : dict, default: None
            Keyword arguments. For allowable keyword arguments, see the
            :meth:`Plotter.add_mesh <pyvista.Plotter.add_mesh>` method.

        """
        ...
    
    def close(self): # -> None:
        """Close the plotter for PyVistaQT."""
        ...
    


