"""
This type stub file was generated by pyright.
"""

class GraphSetup:
    """Defines the frequency and time limits of the exported responses.

    This class allows you to configure the graph limit parameters.
    """
    def __init__(self) -> None:
        ...
    
    @property
    def minimum_frequency(self) -> str:
        """Minimum frequency value for exporting frequency and S parameter responses. The default is ``200 MHz``.

        Returns
        -------
        str
        """
        ...
    
    @minimum_frequency.setter
    def minimum_frequency(self, min_freq_string): # -> None:
        ...
    
    @property
    def maximum_frequency(self) -> str:
        """Maximum frequency value for exporting frequency and S parameters responses. The default is ``5 GHz``.

        Returns
        -------
        str
        """
        ...
    
    @maximum_frequency.setter
    def maximum_frequency(self, max_freq_string): # -> None:
        ...
    
    @property
    def minimum_time(self) -> str:
        """Minimum time value for exporting time response. The default is ``0 s``.

        Returns
        -------
        str
        """
        ...
    
    @minimum_time.setter
    def minimum_time(self, min_time_string): # -> None:
        ...
    
    @property
    def maximum_time(self) -> str:
        """Maximum time value for exporting time response. The default is ``10 ns``.

        Returns
        -------
        str
        """
        ...
    
    @maximum_time.setter
    def maximum_time(self, max_time_string): # -> None:
        ...
    


